main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Publications
    url: '#publications'
    weight: 20
  - name: Awards
    url: '#awards'
    weight: 30
  - name: Press
    url: '#press'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 50
  - name: CV
    url: https://cazimmerman.github.io/files/zimmerman-cv.pdf
    weight: 60
